/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// GetChildrenResponse struct for GetChildrenResponse
type GetChildrenResponse struct {
	Data *GetChildrenResponseData `json:"data,omitempty"`
}

// NewGetChildrenResponse instantiates a new GetChildrenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetChildrenResponse() *GetChildrenResponse {
	this := GetChildrenResponse{}
	return &this
}

// NewGetChildrenResponseWithDefaults instantiates a new GetChildrenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetChildrenResponseWithDefaults() *GetChildrenResponse {
	this := GetChildrenResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetChildrenResponse) GetData() GetChildrenResponseData {
	if o == nil || o.Data == nil {
		var ret GetChildrenResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponse) GetDataOk() (*GetChildrenResponseData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetChildrenResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GetChildrenResponseData and assigns it to the Data field.
func (o *GetChildrenResponse) SetData(v GetChildrenResponseData) {
	o.Data = &v
}

func (o GetChildrenResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetChildrenResponse struct {
	value *GetChildrenResponse
	isSet bool
}

func (v NullableGetChildrenResponse) Get() *GetChildrenResponse {
	return v.value
}

func (v *NullableGetChildrenResponse) Set(val *GetChildrenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetChildrenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetChildrenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetChildrenResponse(val *GetChildrenResponse) *NullableGetChildrenResponse {
	return &NullableGetChildrenResponse{value: val, isSet: true}
}

func (v NullableGetChildrenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetChildrenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


