/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// GetProductDetailsResponseConfig struct for GetProductDetailsResponseConfig
type GetProductDetailsResponseConfig struct {
	Bonus *bool `json:"bonus,omitempty"`
	Brand *bool `json:"brand,omitempty"`
	BuyButton *bool `json:"buy_button,omitempty"`
	CompareButton *bool `json:"compare_button,omitempty"`
	Description *bool `json:"description,omitempty"`
	Gift *bool `json:"gift,omitempty"`
	Image *bool `json:"image,omitempty"`
	OldPrice *bool `json:"old_price,omitempty"`
	Pictograms *bool `json:"pictograms,omitempty"`
	Price *bool `json:"price,omitempty"`
	PromoPrice *bool `json:"promo_price,omitempty"`
	Rating *bool `json:"rating,omitempty"`
	Status *bool `json:"status,omitempty"`
	Tags *bool `json:"tags,omitempty"`
	Title *bool `json:"title,omitempty"`
	Variables *bool `json:"variables,omitempty"`
	WishlistButton *bool `json:"wishlist_button,omitempty"`
}

// NewGetProductDetailsResponseConfig instantiates a new GetProductDetailsResponseConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProductDetailsResponseConfig() *GetProductDetailsResponseConfig {
	this := GetProductDetailsResponseConfig{}
	return &this
}

// NewGetProductDetailsResponseConfigWithDefaults instantiates a new GetProductDetailsResponseConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProductDetailsResponseConfigWithDefaults() *GetProductDetailsResponseConfig {
	this := GetProductDetailsResponseConfig{}
	return &this
}

// GetBonus returns the Bonus field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetBonus() bool {
	if o == nil || o.Bonus == nil {
		var ret bool
		return ret
	}
	return *o.Bonus
}

// GetBonusOk returns a tuple with the Bonus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetBonusOk() (*bool, bool) {
	if o == nil || o.Bonus == nil {
		return nil, false
	}
	return o.Bonus, true
}

// HasBonus returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasBonus() bool {
	if o != nil && o.Bonus != nil {
		return true
	}

	return false
}

// SetBonus gets a reference to the given bool and assigns it to the Bonus field.
func (o *GetProductDetailsResponseConfig) SetBonus(v bool) {
	o.Bonus = &v
}

// GetBrand returns the Brand field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetBrand() bool {
	if o == nil || o.Brand == nil {
		var ret bool
		return ret
	}
	return *o.Brand
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetBrandOk() (*bool, bool) {
	if o == nil || o.Brand == nil {
		return nil, false
	}
	return o.Brand, true
}

// HasBrand returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasBrand() bool {
	if o != nil && o.Brand != nil {
		return true
	}

	return false
}

// SetBrand gets a reference to the given bool and assigns it to the Brand field.
func (o *GetProductDetailsResponseConfig) SetBrand(v bool) {
	o.Brand = &v
}

// GetBuyButton returns the BuyButton field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetBuyButton() bool {
	if o == nil || o.BuyButton == nil {
		var ret bool
		return ret
	}
	return *o.BuyButton
}

// GetBuyButtonOk returns a tuple with the BuyButton field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetBuyButtonOk() (*bool, bool) {
	if o == nil || o.BuyButton == nil {
		return nil, false
	}
	return o.BuyButton, true
}

// HasBuyButton returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasBuyButton() bool {
	if o != nil && o.BuyButton != nil {
		return true
	}

	return false
}

// SetBuyButton gets a reference to the given bool and assigns it to the BuyButton field.
func (o *GetProductDetailsResponseConfig) SetBuyButton(v bool) {
	o.BuyButton = &v
}

// GetCompareButton returns the CompareButton field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetCompareButton() bool {
	if o == nil || o.CompareButton == nil {
		var ret bool
		return ret
	}
	return *o.CompareButton
}

// GetCompareButtonOk returns a tuple with the CompareButton field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetCompareButtonOk() (*bool, bool) {
	if o == nil || o.CompareButton == nil {
		return nil, false
	}
	return o.CompareButton, true
}

// HasCompareButton returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasCompareButton() bool {
	if o != nil && o.CompareButton != nil {
		return true
	}

	return false
}

// SetCompareButton gets a reference to the given bool and assigns it to the CompareButton field.
func (o *GetProductDetailsResponseConfig) SetCompareButton(v bool) {
	o.CompareButton = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetDescription() bool {
	if o == nil || o.Description == nil {
		var ret bool
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetDescriptionOk() (*bool, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given bool and assigns it to the Description field.
func (o *GetProductDetailsResponseConfig) SetDescription(v bool) {
	o.Description = &v
}

// GetGift returns the Gift field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetGift() bool {
	if o == nil || o.Gift == nil {
		var ret bool
		return ret
	}
	return *o.Gift
}

// GetGiftOk returns a tuple with the Gift field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetGiftOk() (*bool, bool) {
	if o == nil || o.Gift == nil {
		return nil, false
	}
	return o.Gift, true
}

// HasGift returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasGift() bool {
	if o != nil && o.Gift != nil {
		return true
	}

	return false
}

// SetGift gets a reference to the given bool and assigns it to the Gift field.
func (o *GetProductDetailsResponseConfig) SetGift(v bool) {
	o.Gift = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetImage() bool {
	if o == nil || o.Image == nil {
		var ret bool
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetImageOk() (*bool, bool) {
	if o == nil || o.Image == nil {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasImage() bool {
	if o != nil && o.Image != nil {
		return true
	}

	return false
}

// SetImage gets a reference to the given bool and assigns it to the Image field.
func (o *GetProductDetailsResponseConfig) SetImage(v bool) {
	o.Image = &v
}

// GetOldPrice returns the OldPrice field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetOldPrice() bool {
	if o == nil || o.OldPrice == nil {
		var ret bool
		return ret
	}
	return *o.OldPrice
}

// GetOldPriceOk returns a tuple with the OldPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetOldPriceOk() (*bool, bool) {
	if o == nil || o.OldPrice == nil {
		return nil, false
	}
	return o.OldPrice, true
}

// HasOldPrice returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasOldPrice() bool {
	if o != nil && o.OldPrice != nil {
		return true
	}

	return false
}

// SetOldPrice gets a reference to the given bool and assigns it to the OldPrice field.
func (o *GetProductDetailsResponseConfig) SetOldPrice(v bool) {
	o.OldPrice = &v
}

// GetPictograms returns the Pictograms field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetPictograms() bool {
	if o == nil || o.Pictograms == nil {
		var ret bool
		return ret
	}
	return *o.Pictograms
}

// GetPictogramsOk returns a tuple with the Pictograms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetPictogramsOk() (*bool, bool) {
	if o == nil || o.Pictograms == nil {
		return nil, false
	}
	return o.Pictograms, true
}

// HasPictograms returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasPictograms() bool {
	if o != nil && o.Pictograms != nil {
		return true
	}

	return false
}

// SetPictograms gets a reference to the given bool and assigns it to the Pictograms field.
func (o *GetProductDetailsResponseConfig) SetPictograms(v bool) {
	o.Pictograms = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetPrice() bool {
	if o == nil || o.Price == nil {
		var ret bool
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetPriceOk() (*bool, bool) {
	if o == nil || o.Price == nil {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasPrice() bool {
	if o != nil && o.Price != nil {
		return true
	}

	return false
}

// SetPrice gets a reference to the given bool and assigns it to the Price field.
func (o *GetProductDetailsResponseConfig) SetPrice(v bool) {
	o.Price = &v
}

// GetPromoPrice returns the PromoPrice field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetPromoPrice() bool {
	if o == nil || o.PromoPrice == nil {
		var ret bool
		return ret
	}
	return *o.PromoPrice
}

// GetPromoPriceOk returns a tuple with the PromoPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetPromoPriceOk() (*bool, bool) {
	if o == nil || o.PromoPrice == nil {
		return nil, false
	}
	return o.PromoPrice, true
}

// HasPromoPrice returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasPromoPrice() bool {
	if o != nil && o.PromoPrice != nil {
		return true
	}

	return false
}

// SetPromoPrice gets a reference to the given bool and assigns it to the PromoPrice field.
func (o *GetProductDetailsResponseConfig) SetPromoPrice(v bool) {
	o.PromoPrice = &v
}

// GetRating returns the Rating field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetRating() bool {
	if o == nil || o.Rating == nil {
		var ret bool
		return ret
	}
	return *o.Rating
}

// GetRatingOk returns a tuple with the Rating field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetRatingOk() (*bool, bool) {
	if o == nil || o.Rating == nil {
		return nil, false
	}
	return o.Rating, true
}

// HasRating returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasRating() bool {
	if o != nil && o.Rating != nil {
		return true
	}

	return false
}

// SetRating gets a reference to the given bool and assigns it to the Rating field.
func (o *GetProductDetailsResponseConfig) SetRating(v bool) {
	o.Rating = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetStatus() bool {
	if o == nil || o.Status == nil {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetStatusOk() (*bool, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *GetProductDetailsResponseConfig) SetStatus(v bool) {
	o.Status = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetTags() bool {
	if o == nil || o.Tags == nil {
		var ret bool
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetTagsOk() (*bool, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given bool and assigns it to the Tags field.
func (o *GetProductDetailsResponseConfig) SetTags(v bool) {
	o.Tags = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetTitle() bool {
	if o == nil || o.Title == nil {
		var ret bool
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetTitleOk() (*bool, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given bool and assigns it to the Title field.
func (o *GetProductDetailsResponseConfig) SetTitle(v bool) {
	o.Title = &v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetVariables() bool {
	if o == nil || o.Variables == nil {
		var ret bool
		return ret
	}
	return *o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetVariablesOk() (*bool, bool) {
	if o == nil || o.Variables == nil {
		return nil, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasVariables() bool {
	if o != nil && o.Variables != nil {
		return true
	}

	return false
}

// SetVariables gets a reference to the given bool and assigns it to the Variables field.
func (o *GetProductDetailsResponseConfig) SetVariables(v bool) {
	o.Variables = &v
}

// GetWishlistButton returns the WishlistButton field value if set, zero value otherwise.
func (o *GetProductDetailsResponseConfig) GetWishlistButton() bool {
	if o == nil || o.WishlistButton == nil {
		var ret bool
		return ret
	}
	return *o.WishlistButton
}

// GetWishlistButtonOk returns a tuple with the WishlistButton field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseConfig) GetWishlistButtonOk() (*bool, bool) {
	if o == nil || o.WishlistButton == nil {
		return nil, false
	}
	return o.WishlistButton, true
}

// HasWishlistButton returns a boolean if a field has been set.
func (o *GetProductDetailsResponseConfig) HasWishlistButton() bool {
	if o != nil && o.WishlistButton != nil {
		return true
	}

	return false
}

// SetWishlistButton gets a reference to the given bool and assigns it to the WishlistButton field.
func (o *GetProductDetailsResponseConfig) SetWishlistButton(v bool) {
	o.WishlistButton = &v
}

func (o GetProductDetailsResponseConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Bonus != nil {
		toSerialize["bonus"] = o.Bonus
	}
	if o.Brand != nil {
		toSerialize["brand"] = o.Brand
	}
	if o.BuyButton != nil {
		toSerialize["buy_button"] = o.BuyButton
	}
	if o.CompareButton != nil {
		toSerialize["compare_button"] = o.CompareButton
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Gift != nil {
		toSerialize["gift"] = o.Gift
	}
	if o.Image != nil {
		toSerialize["image"] = o.Image
	}
	if o.OldPrice != nil {
		toSerialize["old_price"] = o.OldPrice
	}
	if o.Pictograms != nil {
		toSerialize["pictograms"] = o.Pictograms
	}
	if o.Price != nil {
		toSerialize["price"] = o.Price
	}
	if o.PromoPrice != nil {
		toSerialize["promo_price"] = o.PromoPrice
	}
	if o.Rating != nil {
		toSerialize["rating"] = o.Rating
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	if o.Variables != nil {
		toSerialize["variables"] = o.Variables
	}
	if o.WishlistButton != nil {
		toSerialize["wishlist_button"] = o.WishlistButton
	}
	return json.Marshal(toSerialize)
}

type NullableGetProductDetailsResponseConfig struct {
	value *GetProductDetailsResponseConfig
	isSet bool
}

func (v NullableGetProductDetailsResponseConfig) Get() *GetProductDetailsResponseConfig {
	return v.value
}

func (v *NullableGetProductDetailsResponseConfig) Set(val *GetProductDetailsResponseConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProductDetailsResponseConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProductDetailsResponseConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProductDetailsResponseConfig(val *GetProductDetailsResponseConfig) *NullableGetProductDetailsResponseConfig {
	return &NullableGetProductDetailsResponseConfig{value: val, isSet: true}
}

func (v NullableGetProductDetailsResponseConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProductDetailsResponseConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


