/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// GetProductsInCategoryResponse struct for GetProductsInCategoryResponse
type GetProductsInCategoryResponse struct {
	Data *GetProductsInCategoryResponseData `json:"data,omitempty"`
}

// NewGetProductsInCategoryResponse instantiates a new GetProductsInCategoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProductsInCategoryResponse() *GetProductsInCategoryResponse {
	this := GetProductsInCategoryResponse{}
	return &this
}

// NewGetProductsInCategoryResponseWithDefaults instantiates a new GetProductsInCategoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProductsInCategoryResponseWithDefaults() *GetProductsInCategoryResponse {
	this := GetProductsInCategoryResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetProductsInCategoryResponse) GetData() GetProductsInCategoryResponseData {
	if o == nil || o.Data == nil {
		var ret GetProductsInCategoryResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductsInCategoryResponse) GetDataOk() (*GetProductsInCategoryResponseData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetProductsInCategoryResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GetProductsInCategoryResponseData and assigns it to the Data field.
func (o *GetProductsInCategoryResponse) SetData(v GetProductsInCategoryResponseData) {
	o.Data = &v
}

func (o GetProductsInCategoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetProductsInCategoryResponse struct {
	value *GetProductsInCategoryResponse
	isSet bool
}

func (v NullableGetProductsInCategoryResponse) Get() *GetProductsInCategoryResponse {
	return v.value
}

func (v *NullableGetProductsInCategoryResponse) Set(val *GetProductsInCategoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProductsInCategoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProductsInCategoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProductsInCategoryResponse(val *GetProductsInCategoryResponse) *NullableGetProductsInCategoryResponse {
	return &NullableGetProductsInCategoryResponse{value: val, isSet: true}
}

func (v NullableGetProductsInCategoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProductsInCategoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


