/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// GetChildrenResponseDataCurrent struct for GetChildrenResponseDataCurrent
type GetChildrenResponseDataCurrent struct {
	AllowIndexThreeParameters *bool `json:"allow_index_three_parameters,omitempty"`
	Count *int64 `json:"count,omitempty"`
	Href *string `json:"href,omitempty"`
	Id *int64 `json:"id,omitempty"`
	IsRozetkaTop *bool `json:"is_rozetka_top,omitempty"`
	LeftKey *int64 `json:"left_key,omitempty"`
	Level *int64 `json:"level,omitempty"`
	Mpath *string `json:"mpath,omitempty"`
	Name *string `json:"name,omitempty"`
	ParentId *int64 `json:"parent_id,omitempty"`
	RightKey *int64 `json:"right_key,omitempty"`
	RootId *int64 `json:"root_id,omitempty"`
	RzMpath *string `json:"rz_mpath,omitempty"`
	Status *string `json:"status,omitempty"`
	Subdomain interface{} `json:"subdomain,omitempty"`
	Title *string `json:"title,omitempty"`
	TitlesMode *string `json:"titles_mode,omitempty"`
}

// NewGetChildrenResponseDataCurrent instantiates a new GetChildrenResponseDataCurrent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetChildrenResponseDataCurrent() *GetChildrenResponseDataCurrent {
	this := GetChildrenResponseDataCurrent{}
	return &this
}

// NewGetChildrenResponseDataCurrentWithDefaults instantiates a new GetChildrenResponseDataCurrent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetChildrenResponseDataCurrentWithDefaults() *GetChildrenResponseDataCurrent {
	this := GetChildrenResponseDataCurrent{}
	return &this
}

// GetAllowIndexThreeParameters returns the AllowIndexThreeParameters field value if set, zero value otherwise.
func (o *GetChildrenResponseDataCurrent) GetAllowIndexThreeParameters() bool {
	if o == nil || o.AllowIndexThreeParameters == nil {
		var ret bool
		return ret
	}
	return *o.AllowIndexThreeParameters
}

// GetAllowIndexThreeParametersOk returns a tuple with the AllowIndexThreeParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponseDataCurrent) GetAllowIndexThreeParametersOk() (*bool, bool) {
	if o == nil || o.AllowIndexThreeParameters == nil {
		return nil, false
	}
	return o.AllowIndexThreeParameters, true
}

// HasAllowIndexThreeParameters returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasAllowIndexThreeParameters() bool {
	if o != nil && o.AllowIndexThreeParameters != nil {
		return true
	}

	return false
}

// SetAllowIndexThreeParameters gets a reference to the given bool and assigns it to the AllowIndexThreeParameters field.
func (o *GetChildrenResponseDataCurrent) SetAllowIndexThreeParameters(v bool) {
	o.AllowIndexThreeParameters = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *GetChildrenResponseDataCurrent) GetCount() int64 {
	if o == nil || o.Count == nil {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponseDataCurrent) GetCountOk() (*int64, bool) {
	if o == nil || o.Count == nil {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasCount() bool {
	if o != nil && o.Count != nil {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *GetChildrenResponseDataCurrent) SetCount(v int64) {
	o.Count = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *GetChildrenResponseDataCurrent) GetHref() string {
	if o == nil || o.Href == nil {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponseDataCurrent) GetHrefOk() (*string, bool) {
	if o == nil || o.Href == nil {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasHref() bool {
	if o != nil && o.Href != nil {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *GetChildrenResponseDataCurrent) SetHref(v string) {
	o.Href = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetChildrenResponseDataCurrent) GetId() int64 {
	if o == nil || o.Id == nil {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponseDataCurrent) GetIdOk() (*int64, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *GetChildrenResponseDataCurrent) SetId(v int64) {
	o.Id = &v
}

// GetIsRozetkaTop returns the IsRozetkaTop field value if set, zero value otherwise.
func (o *GetChildrenResponseDataCurrent) GetIsRozetkaTop() bool {
	if o == nil || o.IsRozetkaTop == nil {
		var ret bool
		return ret
	}
	return *o.IsRozetkaTop
}

// GetIsRozetkaTopOk returns a tuple with the IsRozetkaTop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponseDataCurrent) GetIsRozetkaTopOk() (*bool, bool) {
	if o == nil || o.IsRozetkaTop == nil {
		return nil, false
	}
	return o.IsRozetkaTop, true
}

// HasIsRozetkaTop returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasIsRozetkaTop() bool {
	if o != nil && o.IsRozetkaTop != nil {
		return true
	}

	return false
}

// SetIsRozetkaTop gets a reference to the given bool and assigns it to the IsRozetkaTop field.
func (o *GetChildrenResponseDataCurrent) SetIsRozetkaTop(v bool) {
	o.IsRozetkaTop = &v
}

// GetLeftKey returns the LeftKey field value if set, zero value otherwise.
func (o *GetChildrenResponseDataCurrent) GetLeftKey() int64 {
	if o == nil || o.LeftKey == nil {
		var ret int64
		return ret
	}
	return *o.LeftKey
}

// GetLeftKeyOk returns a tuple with the LeftKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponseDataCurrent) GetLeftKeyOk() (*int64, bool) {
	if o == nil || o.LeftKey == nil {
		return nil, false
	}
	return o.LeftKey, true
}

// HasLeftKey returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasLeftKey() bool {
	if o != nil && o.LeftKey != nil {
		return true
	}

	return false
}

// SetLeftKey gets a reference to the given int64 and assigns it to the LeftKey field.
func (o *GetChildrenResponseDataCurrent) SetLeftKey(v int64) {
	o.LeftKey = &v
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *GetChildrenResponseDataCurrent) GetLevel() int64 {
	if o == nil || o.Level == nil {
		var ret int64
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponseDataCurrent) GetLevelOk() (*int64, bool) {
	if o == nil || o.Level == nil {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasLevel() bool {
	if o != nil && o.Level != nil {
		return true
	}

	return false
}

// SetLevel gets a reference to the given int64 and assigns it to the Level field.
func (o *GetChildrenResponseDataCurrent) SetLevel(v int64) {
	o.Level = &v
}

// GetMpath returns the Mpath field value if set, zero value otherwise.
func (o *GetChildrenResponseDataCurrent) GetMpath() string {
	if o == nil || o.Mpath == nil {
		var ret string
		return ret
	}
	return *o.Mpath
}

// GetMpathOk returns a tuple with the Mpath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponseDataCurrent) GetMpathOk() (*string, bool) {
	if o == nil || o.Mpath == nil {
		return nil, false
	}
	return o.Mpath, true
}

// HasMpath returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasMpath() bool {
	if o != nil && o.Mpath != nil {
		return true
	}

	return false
}

// SetMpath gets a reference to the given string and assigns it to the Mpath field.
func (o *GetChildrenResponseDataCurrent) SetMpath(v string) {
	o.Mpath = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetChildrenResponseDataCurrent) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponseDataCurrent) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetChildrenResponseDataCurrent) SetName(v string) {
	o.Name = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *GetChildrenResponseDataCurrent) GetParentId() int64 {
	if o == nil || o.ParentId == nil {
		var ret int64
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponseDataCurrent) GetParentIdOk() (*int64, bool) {
	if o == nil || o.ParentId == nil {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasParentId() bool {
	if o != nil && o.ParentId != nil {
		return true
	}

	return false
}

// SetParentId gets a reference to the given int64 and assigns it to the ParentId field.
func (o *GetChildrenResponseDataCurrent) SetParentId(v int64) {
	o.ParentId = &v
}

// GetRightKey returns the RightKey field value if set, zero value otherwise.
func (o *GetChildrenResponseDataCurrent) GetRightKey() int64 {
	if o == nil || o.RightKey == nil {
		var ret int64
		return ret
	}
	return *o.RightKey
}

// GetRightKeyOk returns a tuple with the RightKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponseDataCurrent) GetRightKeyOk() (*int64, bool) {
	if o == nil || o.RightKey == nil {
		return nil, false
	}
	return o.RightKey, true
}

// HasRightKey returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasRightKey() bool {
	if o != nil && o.RightKey != nil {
		return true
	}

	return false
}

// SetRightKey gets a reference to the given int64 and assigns it to the RightKey field.
func (o *GetChildrenResponseDataCurrent) SetRightKey(v int64) {
	o.RightKey = &v
}

// GetRootId returns the RootId field value if set, zero value otherwise.
func (o *GetChildrenResponseDataCurrent) GetRootId() int64 {
	if o == nil || o.RootId == nil {
		var ret int64
		return ret
	}
	return *o.RootId
}

// GetRootIdOk returns a tuple with the RootId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponseDataCurrent) GetRootIdOk() (*int64, bool) {
	if o == nil || o.RootId == nil {
		return nil, false
	}
	return o.RootId, true
}

// HasRootId returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasRootId() bool {
	if o != nil && o.RootId != nil {
		return true
	}

	return false
}

// SetRootId gets a reference to the given int64 and assigns it to the RootId field.
func (o *GetChildrenResponseDataCurrent) SetRootId(v int64) {
	o.RootId = &v
}

// GetRzMpath returns the RzMpath field value if set, zero value otherwise.
func (o *GetChildrenResponseDataCurrent) GetRzMpath() string {
	if o == nil || o.RzMpath == nil {
		var ret string
		return ret
	}
	return *o.RzMpath
}

// GetRzMpathOk returns a tuple with the RzMpath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponseDataCurrent) GetRzMpathOk() (*string, bool) {
	if o == nil || o.RzMpath == nil {
		return nil, false
	}
	return o.RzMpath, true
}

// HasRzMpath returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasRzMpath() bool {
	if o != nil && o.RzMpath != nil {
		return true
	}

	return false
}

// SetRzMpath gets a reference to the given string and assigns it to the RzMpath field.
func (o *GetChildrenResponseDataCurrent) SetRzMpath(v string) {
	o.RzMpath = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetChildrenResponseDataCurrent) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponseDataCurrent) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetChildrenResponseDataCurrent) SetStatus(v string) {
	o.Status = &v
}

// GetSubdomain returns the Subdomain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetChildrenResponseDataCurrent) GetSubdomain() interface{} {
	if o == nil  {
		var ret interface{}
		return ret
	}
	return o.Subdomain
}

// GetSubdomainOk returns a tuple with the Subdomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetChildrenResponseDataCurrent) GetSubdomainOk() (*interface{}, bool) {
	if o == nil || o.Subdomain == nil {
		return nil, false
	}
	return &o.Subdomain, true
}

// HasSubdomain returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasSubdomain() bool {
	if o != nil && o.Subdomain != nil {
		return true
	}

	return false
}

// SetSubdomain gets a reference to the given interface{} and assigns it to the Subdomain field.
func (o *GetChildrenResponseDataCurrent) SetSubdomain(v interface{}) {
	o.Subdomain = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GetChildrenResponseDataCurrent) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponseDataCurrent) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GetChildrenResponseDataCurrent) SetTitle(v string) {
	o.Title = &v
}

// GetTitlesMode returns the TitlesMode field value if set, zero value otherwise.
func (o *GetChildrenResponseDataCurrent) GetTitlesMode() string {
	if o == nil || o.TitlesMode == nil {
		var ret string
		return ret
	}
	return *o.TitlesMode
}

// GetTitlesModeOk returns a tuple with the TitlesMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildrenResponseDataCurrent) GetTitlesModeOk() (*string, bool) {
	if o == nil || o.TitlesMode == nil {
		return nil, false
	}
	return o.TitlesMode, true
}

// HasTitlesMode returns a boolean if a field has been set.
func (o *GetChildrenResponseDataCurrent) HasTitlesMode() bool {
	if o != nil && o.TitlesMode != nil {
		return true
	}

	return false
}

// SetTitlesMode gets a reference to the given string and assigns it to the TitlesMode field.
func (o *GetChildrenResponseDataCurrent) SetTitlesMode(v string) {
	o.TitlesMode = &v
}

func (o GetChildrenResponseDataCurrent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AllowIndexThreeParameters != nil {
		toSerialize["allow_index_three_parameters"] = o.AllowIndexThreeParameters
	}
	if o.Count != nil {
		toSerialize["count"] = o.Count
	}
	if o.Href != nil {
		toSerialize["href"] = o.Href
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.IsRozetkaTop != nil {
		toSerialize["is_rozetka_top"] = o.IsRozetkaTop
	}
	if o.LeftKey != nil {
		toSerialize["left_key"] = o.LeftKey
	}
	if o.Level != nil {
		toSerialize["level"] = o.Level
	}
	if o.Mpath != nil {
		toSerialize["mpath"] = o.Mpath
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.ParentId != nil {
		toSerialize["parent_id"] = o.ParentId
	}
	if o.RightKey != nil {
		toSerialize["right_key"] = o.RightKey
	}
	if o.RootId != nil {
		toSerialize["root_id"] = o.RootId
	}
	if o.RzMpath != nil {
		toSerialize["rz_mpath"] = o.RzMpath
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Subdomain != nil {
		toSerialize["subdomain"] = o.Subdomain
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	if o.TitlesMode != nil {
		toSerialize["titles_mode"] = o.TitlesMode
	}
	return json.Marshal(toSerialize)
}

type NullableGetChildrenResponseDataCurrent struct {
	value *GetChildrenResponseDataCurrent
	isSet bool
}

func (v NullableGetChildrenResponseDataCurrent) Get() *GetChildrenResponseDataCurrent {
	return v.value
}

func (v *NullableGetChildrenResponseDataCurrent) Set(val *GetChildrenResponseDataCurrent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetChildrenResponseDataCurrent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetChildrenResponseDataCurrent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetChildrenResponseDataCurrent(val *GetChildrenResponseDataCurrent) *NullableGetChildrenResponseDataCurrent {
	return &NullableGetChildrenResponseDataCurrent{value: val, isSet: true}
}

func (v NullableGetChildrenResponseDataCurrent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetChildrenResponseDataCurrent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


