/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// GetProductDetailsResponseData struct for GetProductDetailsResponseData
type GetProductDetailsResponseData struct {
	Brand *string `json:"brand,omitempty"`
	BrandId *int64 `json:"brand_id,omitempty"`
	CategoryId *int64 `json:"category_id,omitempty"`
	CommentsAmount *float64 `json:"comments_amount,omitempty"`
	CommentsMark *float64 `json:"comments_mark,omitempty"`
	Config *GetProductDetailsResponseConfig `json:"config,omitempty"`
	Discount *float64 `json:"discount,omitempty"`
	Dispatch *float64 `json:"dispatch,omitempty"`
	Docket *string `json:"docket,omitempty"`
	Gift interface{} `json:"gift,omitempty"`
	GroupId *int64 `json:"group_id,omitempty"`
	GroupName interface{} `json:"group_name,omitempty"`
	GroupTitle interface{} `json:"group_title,omitempty"`
	Groups *[]interface{} `json:"groups,omitempty"`
	Href *string `json:"href,omitempty"`
	Id int64 `json:"id"`
	ImageMain *string `json:"image_main,omitempty"`
	Images *GetProductDetailsResponseImages `json:"images,omitempty"`
	IsGroupPrimary *float64 `json:"is_group_primary,omitempty"`
	IsNeedStreetId *bool `json:"is_need_street_id,omitempty"`
	MerchantId *float64 `json:"merchant_id,omitempty"`
	Mpath *string `json:"mpath,omitempty"`
	OldPrice *float64 `json:"old_price,omitempty"`
	ParentCategoryId *float64 `json:"parent_category_id,omitempty"`
	PlBonusChargePcs *float64 `json:"pl_bonus_charge_pcs,omitempty"`
	PlUseInstantBonus *float64 `json:"pl_use_instant_bonus,omitempty"`
	Premium *float64 `json:"premium,omitempty"`
	Preorder *float64 `json:"preorder,omitempty"`
	Price *float64 `json:"price,omitempty"`
	PricePcs *string `json:"price_pcs,omitempty"`
	PrimaryGoodTitle interface{} `json:"primary_good_title,omitempty"`
	SellStatus *string `json:"sell_status,omitempty"`
	SellerId *float64 `json:"seller_id,omitempty"`
	Stars *string `json:"stars,omitempty"`
	State *string `json:"state,omitempty"`
	Status *string `json:"status,omitempty"`
	StatusInherited *string `json:"status_inherited,omitempty"`
	Tag interface{} `json:"tag,omitempty"`
	Title string `json:"title"`
	TitleMode interface{} `json:"title_mode,omitempty"`
	TitleSuffix NullableString `json:"title_suffix,omitempty"`
	UseGroupLinks interface{} `json:"use_group_links,omitempty"`
}

// NewGetProductDetailsResponseData instantiates a new GetProductDetailsResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProductDetailsResponseData(id int64, title string) *GetProductDetailsResponseData {
	this := GetProductDetailsResponseData{}
	this.Id = id
	this.Title = title
	return &this
}

// NewGetProductDetailsResponseDataWithDefaults instantiates a new GetProductDetailsResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProductDetailsResponseDataWithDefaults() *GetProductDetailsResponseData {
	this := GetProductDetailsResponseData{}
	return &this
}

// GetBrand returns the Brand field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetBrand() string {
	if o == nil || o.Brand == nil {
		var ret string
		return ret
	}
	return *o.Brand
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetBrandOk() (*string, bool) {
	if o == nil || o.Brand == nil {
		return nil, false
	}
	return o.Brand, true
}

// HasBrand returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasBrand() bool {
	if o != nil && o.Brand != nil {
		return true
	}

	return false
}

// SetBrand gets a reference to the given string and assigns it to the Brand field.
func (o *GetProductDetailsResponseData) SetBrand(v string) {
	o.Brand = &v
}

// GetBrandId returns the BrandId field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetBrandId() int64 {
	if o == nil || o.BrandId == nil {
		var ret int64
		return ret
	}
	return *o.BrandId
}

// GetBrandIdOk returns a tuple with the BrandId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetBrandIdOk() (*int64, bool) {
	if o == nil || o.BrandId == nil {
		return nil, false
	}
	return o.BrandId, true
}

// HasBrandId returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasBrandId() bool {
	if o != nil && o.BrandId != nil {
		return true
	}

	return false
}

// SetBrandId gets a reference to the given int64 and assigns it to the BrandId field.
func (o *GetProductDetailsResponseData) SetBrandId(v int64) {
	o.BrandId = &v
}

// GetCategoryId returns the CategoryId field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetCategoryId() int64 {
	if o == nil || o.CategoryId == nil {
		var ret int64
		return ret
	}
	return *o.CategoryId
}

// GetCategoryIdOk returns a tuple with the CategoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetCategoryIdOk() (*int64, bool) {
	if o == nil || o.CategoryId == nil {
		return nil, false
	}
	return o.CategoryId, true
}

// HasCategoryId returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasCategoryId() bool {
	if o != nil && o.CategoryId != nil {
		return true
	}

	return false
}

// SetCategoryId gets a reference to the given int64 and assigns it to the CategoryId field.
func (o *GetProductDetailsResponseData) SetCategoryId(v int64) {
	o.CategoryId = &v
}

// GetCommentsAmount returns the CommentsAmount field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetCommentsAmount() float64 {
	if o == nil || o.CommentsAmount == nil {
		var ret float64
		return ret
	}
	return *o.CommentsAmount
}

// GetCommentsAmountOk returns a tuple with the CommentsAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetCommentsAmountOk() (*float64, bool) {
	if o == nil || o.CommentsAmount == nil {
		return nil, false
	}
	return o.CommentsAmount, true
}

// HasCommentsAmount returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasCommentsAmount() bool {
	if o != nil && o.CommentsAmount != nil {
		return true
	}

	return false
}

// SetCommentsAmount gets a reference to the given float64 and assigns it to the CommentsAmount field.
func (o *GetProductDetailsResponseData) SetCommentsAmount(v float64) {
	o.CommentsAmount = &v
}

// GetCommentsMark returns the CommentsMark field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetCommentsMark() float64 {
	if o == nil || o.CommentsMark == nil {
		var ret float64
		return ret
	}
	return *o.CommentsMark
}

// GetCommentsMarkOk returns a tuple with the CommentsMark field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetCommentsMarkOk() (*float64, bool) {
	if o == nil || o.CommentsMark == nil {
		return nil, false
	}
	return o.CommentsMark, true
}

// HasCommentsMark returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasCommentsMark() bool {
	if o != nil && o.CommentsMark != nil {
		return true
	}

	return false
}

// SetCommentsMark gets a reference to the given float64 and assigns it to the CommentsMark field.
func (o *GetProductDetailsResponseData) SetCommentsMark(v float64) {
	o.CommentsMark = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetConfig() GetProductDetailsResponseConfig {
	if o == nil || o.Config == nil {
		var ret GetProductDetailsResponseConfig
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetConfigOk() (*GetProductDetailsResponseConfig, bool) {
	if o == nil || o.Config == nil {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasConfig() bool {
	if o != nil && o.Config != nil {
		return true
	}

	return false
}

// SetConfig gets a reference to the given GetProductDetailsResponseConfig and assigns it to the Config field.
func (o *GetProductDetailsResponseData) SetConfig(v GetProductDetailsResponseConfig) {
	o.Config = &v
}

// GetDiscount returns the Discount field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetDiscount() float64 {
	if o == nil || o.Discount == nil {
		var ret float64
		return ret
	}
	return *o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetDiscountOk() (*float64, bool) {
	if o == nil || o.Discount == nil {
		return nil, false
	}
	return o.Discount, true
}

// HasDiscount returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasDiscount() bool {
	if o != nil && o.Discount != nil {
		return true
	}

	return false
}

// SetDiscount gets a reference to the given float64 and assigns it to the Discount field.
func (o *GetProductDetailsResponseData) SetDiscount(v float64) {
	o.Discount = &v
}

// GetDispatch returns the Dispatch field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetDispatch() float64 {
	if o == nil || o.Dispatch == nil {
		var ret float64
		return ret
	}
	return *o.Dispatch
}

// GetDispatchOk returns a tuple with the Dispatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetDispatchOk() (*float64, bool) {
	if o == nil || o.Dispatch == nil {
		return nil, false
	}
	return o.Dispatch, true
}

// HasDispatch returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasDispatch() bool {
	if o != nil && o.Dispatch != nil {
		return true
	}

	return false
}

// SetDispatch gets a reference to the given float64 and assigns it to the Dispatch field.
func (o *GetProductDetailsResponseData) SetDispatch(v float64) {
	o.Dispatch = &v
}

// GetDocket returns the Docket field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetDocket() string {
	if o == nil || o.Docket == nil {
		var ret string
		return ret
	}
	return *o.Docket
}

// GetDocketOk returns a tuple with the Docket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetDocketOk() (*string, bool) {
	if o == nil || o.Docket == nil {
		return nil, false
	}
	return o.Docket, true
}

// HasDocket returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasDocket() bool {
	if o != nil && o.Docket != nil {
		return true
	}

	return false
}

// SetDocket gets a reference to the given string and assigns it to the Docket field.
func (o *GetProductDetailsResponseData) SetDocket(v string) {
	o.Docket = &v
}

// GetGift returns the Gift field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProductDetailsResponseData) GetGift() interface{} {
	if o == nil  {
		var ret interface{}
		return ret
	}
	return o.Gift
}

// GetGiftOk returns a tuple with the Gift field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProductDetailsResponseData) GetGiftOk() (*interface{}, bool) {
	if o == nil || o.Gift == nil {
		return nil, false
	}
	return &o.Gift, true
}

// HasGift returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasGift() bool {
	if o != nil && o.Gift != nil {
		return true
	}

	return false
}

// SetGift gets a reference to the given interface{} and assigns it to the Gift field.
func (o *GetProductDetailsResponseData) SetGift(v interface{}) {
	o.Gift = v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetGroupId() int64 {
	if o == nil || o.GroupId == nil {
		var ret int64
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetGroupIdOk() (*int64, bool) {
	if o == nil || o.GroupId == nil {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasGroupId() bool {
	if o != nil && o.GroupId != nil {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given int64 and assigns it to the GroupId field.
func (o *GetProductDetailsResponseData) SetGroupId(v int64) {
	o.GroupId = &v
}

// GetGroupName returns the GroupName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProductDetailsResponseData) GetGroupName() interface{} {
	if o == nil  {
		var ret interface{}
		return ret
	}
	return o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProductDetailsResponseData) GetGroupNameOk() (*interface{}, bool) {
	if o == nil || o.GroupName == nil {
		return nil, false
	}
	return &o.GroupName, true
}

// HasGroupName returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasGroupName() bool {
	if o != nil && o.GroupName != nil {
		return true
	}

	return false
}

// SetGroupName gets a reference to the given interface{} and assigns it to the GroupName field.
func (o *GetProductDetailsResponseData) SetGroupName(v interface{}) {
	o.GroupName = v
}

// GetGroupTitle returns the GroupTitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProductDetailsResponseData) GetGroupTitle() interface{} {
	if o == nil  {
		var ret interface{}
		return ret
	}
	return o.GroupTitle
}

// GetGroupTitleOk returns a tuple with the GroupTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProductDetailsResponseData) GetGroupTitleOk() (*interface{}, bool) {
	if o == nil || o.GroupTitle == nil {
		return nil, false
	}
	return &o.GroupTitle, true
}

// HasGroupTitle returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasGroupTitle() bool {
	if o != nil && o.GroupTitle != nil {
		return true
	}

	return false
}

// SetGroupTitle gets a reference to the given interface{} and assigns it to the GroupTitle field.
func (o *GetProductDetailsResponseData) SetGroupTitle(v interface{}) {
	o.GroupTitle = v
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetGroups() []interface{} {
	if o == nil || o.Groups == nil {
		var ret []interface{}
		return ret
	}
	return *o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetGroupsOk() (*[]interface{}, bool) {
	if o == nil || o.Groups == nil {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasGroups() bool {
	if o != nil && o.Groups != nil {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []interface{} and assigns it to the Groups field.
func (o *GetProductDetailsResponseData) SetGroups(v []interface{}) {
	o.Groups = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetHref() string {
	if o == nil || o.Href == nil {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetHrefOk() (*string, bool) {
	if o == nil || o.Href == nil {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasHref() bool {
	if o != nil && o.Href != nil {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *GetProductDetailsResponseData) SetHref(v string) {
	o.Href = &v
}

// GetId returns the Id field value
func (o *GetProductDetailsResponseData) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetIdOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetProductDetailsResponseData) SetId(v int64) {
	o.Id = v
}

// GetImageMain returns the ImageMain field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetImageMain() string {
	if o == nil || o.ImageMain == nil {
		var ret string
		return ret
	}
	return *o.ImageMain
}

// GetImageMainOk returns a tuple with the ImageMain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetImageMainOk() (*string, bool) {
	if o == nil || o.ImageMain == nil {
		return nil, false
	}
	return o.ImageMain, true
}

// HasImageMain returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasImageMain() bool {
	if o != nil && o.ImageMain != nil {
		return true
	}

	return false
}

// SetImageMain gets a reference to the given string and assigns it to the ImageMain field.
func (o *GetProductDetailsResponseData) SetImageMain(v string) {
	o.ImageMain = &v
}

// GetImages returns the Images field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetImages() GetProductDetailsResponseImages {
	if o == nil || o.Images == nil {
		var ret GetProductDetailsResponseImages
		return ret
	}
	return *o.Images
}

// GetImagesOk returns a tuple with the Images field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetImagesOk() (*GetProductDetailsResponseImages, bool) {
	if o == nil || o.Images == nil {
		return nil, false
	}
	return o.Images, true
}

// HasImages returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasImages() bool {
	if o != nil && o.Images != nil {
		return true
	}

	return false
}

// SetImages gets a reference to the given GetProductDetailsResponseImages and assigns it to the Images field.
func (o *GetProductDetailsResponseData) SetImages(v GetProductDetailsResponseImages) {
	o.Images = &v
}

// GetIsGroupPrimary returns the IsGroupPrimary field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetIsGroupPrimary() float64 {
	if o == nil || o.IsGroupPrimary == nil {
		var ret float64
		return ret
	}
	return *o.IsGroupPrimary
}

// GetIsGroupPrimaryOk returns a tuple with the IsGroupPrimary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetIsGroupPrimaryOk() (*float64, bool) {
	if o == nil || o.IsGroupPrimary == nil {
		return nil, false
	}
	return o.IsGroupPrimary, true
}

// HasIsGroupPrimary returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasIsGroupPrimary() bool {
	if o != nil && o.IsGroupPrimary != nil {
		return true
	}

	return false
}

// SetIsGroupPrimary gets a reference to the given float64 and assigns it to the IsGroupPrimary field.
func (o *GetProductDetailsResponseData) SetIsGroupPrimary(v float64) {
	o.IsGroupPrimary = &v
}

// GetIsNeedStreetId returns the IsNeedStreetId field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetIsNeedStreetId() bool {
	if o == nil || o.IsNeedStreetId == nil {
		var ret bool
		return ret
	}
	return *o.IsNeedStreetId
}

// GetIsNeedStreetIdOk returns a tuple with the IsNeedStreetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetIsNeedStreetIdOk() (*bool, bool) {
	if o == nil || o.IsNeedStreetId == nil {
		return nil, false
	}
	return o.IsNeedStreetId, true
}

// HasIsNeedStreetId returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasIsNeedStreetId() bool {
	if o != nil && o.IsNeedStreetId != nil {
		return true
	}

	return false
}

// SetIsNeedStreetId gets a reference to the given bool and assigns it to the IsNeedStreetId field.
func (o *GetProductDetailsResponseData) SetIsNeedStreetId(v bool) {
	o.IsNeedStreetId = &v
}

// GetMerchantId returns the MerchantId field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetMerchantId() float64 {
	if o == nil || o.MerchantId == nil {
		var ret float64
		return ret
	}
	return *o.MerchantId
}

// GetMerchantIdOk returns a tuple with the MerchantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetMerchantIdOk() (*float64, bool) {
	if o == nil || o.MerchantId == nil {
		return nil, false
	}
	return o.MerchantId, true
}

// HasMerchantId returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasMerchantId() bool {
	if o != nil && o.MerchantId != nil {
		return true
	}

	return false
}

// SetMerchantId gets a reference to the given float64 and assigns it to the MerchantId field.
func (o *GetProductDetailsResponseData) SetMerchantId(v float64) {
	o.MerchantId = &v
}

// GetMpath returns the Mpath field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetMpath() string {
	if o == nil || o.Mpath == nil {
		var ret string
		return ret
	}
	return *o.Mpath
}

// GetMpathOk returns a tuple with the Mpath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetMpathOk() (*string, bool) {
	if o == nil || o.Mpath == nil {
		return nil, false
	}
	return o.Mpath, true
}

// HasMpath returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasMpath() bool {
	if o != nil && o.Mpath != nil {
		return true
	}

	return false
}

// SetMpath gets a reference to the given string and assigns it to the Mpath field.
func (o *GetProductDetailsResponseData) SetMpath(v string) {
	o.Mpath = &v
}

// GetOldPrice returns the OldPrice field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetOldPrice() float64 {
	if o == nil || o.OldPrice == nil {
		var ret float64
		return ret
	}
	return *o.OldPrice
}

// GetOldPriceOk returns a tuple with the OldPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetOldPriceOk() (*float64, bool) {
	if o == nil || o.OldPrice == nil {
		return nil, false
	}
	return o.OldPrice, true
}

// HasOldPrice returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasOldPrice() bool {
	if o != nil && o.OldPrice != nil {
		return true
	}

	return false
}

// SetOldPrice gets a reference to the given float64 and assigns it to the OldPrice field.
func (o *GetProductDetailsResponseData) SetOldPrice(v float64) {
	o.OldPrice = &v
}

// GetParentCategoryId returns the ParentCategoryId field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetParentCategoryId() float64 {
	if o == nil || o.ParentCategoryId == nil {
		var ret float64
		return ret
	}
	return *o.ParentCategoryId
}

// GetParentCategoryIdOk returns a tuple with the ParentCategoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetParentCategoryIdOk() (*float64, bool) {
	if o == nil || o.ParentCategoryId == nil {
		return nil, false
	}
	return o.ParentCategoryId, true
}

// HasParentCategoryId returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasParentCategoryId() bool {
	if o != nil && o.ParentCategoryId != nil {
		return true
	}

	return false
}

// SetParentCategoryId gets a reference to the given float64 and assigns it to the ParentCategoryId field.
func (o *GetProductDetailsResponseData) SetParentCategoryId(v float64) {
	o.ParentCategoryId = &v
}

// GetPlBonusChargePcs returns the PlBonusChargePcs field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetPlBonusChargePcs() float64 {
	if o == nil || o.PlBonusChargePcs == nil {
		var ret float64
		return ret
	}
	return *o.PlBonusChargePcs
}

// GetPlBonusChargePcsOk returns a tuple with the PlBonusChargePcs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetPlBonusChargePcsOk() (*float64, bool) {
	if o == nil || o.PlBonusChargePcs == nil {
		return nil, false
	}
	return o.PlBonusChargePcs, true
}

// HasPlBonusChargePcs returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasPlBonusChargePcs() bool {
	if o != nil && o.PlBonusChargePcs != nil {
		return true
	}

	return false
}

// SetPlBonusChargePcs gets a reference to the given float64 and assigns it to the PlBonusChargePcs field.
func (o *GetProductDetailsResponseData) SetPlBonusChargePcs(v float64) {
	o.PlBonusChargePcs = &v
}

// GetPlUseInstantBonus returns the PlUseInstantBonus field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetPlUseInstantBonus() float64 {
	if o == nil || o.PlUseInstantBonus == nil {
		var ret float64
		return ret
	}
	return *o.PlUseInstantBonus
}

// GetPlUseInstantBonusOk returns a tuple with the PlUseInstantBonus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetPlUseInstantBonusOk() (*float64, bool) {
	if o == nil || o.PlUseInstantBonus == nil {
		return nil, false
	}
	return o.PlUseInstantBonus, true
}

// HasPlUseInstantBonus returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasPlUseInstantBonus() bool {
	if o != nil && o.PlUseInstantBonus != nil {
		return true
	}

	return false
}

// SetPlUseInstantBonus gets a reference to the given float64 and assigns it to the PlUseInstantBonus field.
func (o *GetProductDetailsResponseData) SetPlUseInstantBonus(v float64) {
	o.PlUseInstantBonus = &v
}

// GetPremium returns the Premium field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetPremium() float64 {
	if o == nil || o.Premium == nil {
		var ret float64
		return ret
	}
	return *o.Premium
}

// GetPremiumOk returns a tuple with the Premium field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetPremiumOk() (*float64, bool) {
	if o == nil || o.Premium == nil {
		return nil, false
	}
	return o.Premium, true
}

// HasPremium returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasPremium() bool {
	if o != nil && o.Premium != nil {
		return true
	}

	return false
}

// SetPremium gets a reference to the given float64 and assigns it to the Premium field.
func (o *GetProductDetailsResponseData) SetPremium(v float64) {
	o.Premium = &v
}

// GetPreorder returns the Preorder field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetPreorder() float64 {
	if o == nil || o.Preorder == nil {
		var ret float64
		return ret
	}
	return *o.Preorder
}

// GetPreorderOk returns a tuple with the Preorder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetPreorderOk() (*float64, bool) {
	if o == nil || o.Preorder == nil {
		return nil, false
	}
	return o.Preorder, true
}

// HasPreorder returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasPreorder() bool {
	if o != nil && o.Preorder != nil {
		return true
	}

	return false
}

// SetPreorder gets a reference to the given float64 and assigns it to the Preorder field.
func (o *GetProductDetailsResponseData) SetPreorder(v float64) {
	o.Preorder = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetPrice() float64 {
	if o == nil || o.Price == nil {
		var ret float64
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetPriceOk() (*float64, bool) {
	if o == nil || o.Price == nil {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasPrice() bool {
	if o != nil && o.Price != nil {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float64 and assigns it to the Price field.
func (o *GetProductDetailsResponseData) SetPrice(v float64) {
	o.Price = &v
}

// GetPricePcs returns the PricePcs field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetPricePcs() string {
	if o == nil || o.PricePcs == nil {
		var ret string
		return ret
	}
	return *o.PricePcs
}

// GetPricePcsOk returns a tuple with the PricePcs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetPricePcsOk() (*string, bool) {
	if o == nil || o.PricePcs == nil {
		return nil, false
	}
	return o.PricePcs, true
}

// HasPricePcs returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasPricePcs() bool {
	if o != nil && o.PricePcs != nil {
		return true
	}

	return false
}

// SetPricePcs gets a reference to the given string and assigns it to the PricePcs field.
func (o *GetProductDetailsResponseData) SetPricePcs(v string) {
	o.PricePcs = &v
}

// GetPrimaryGoodTitle returns the PrimaryGoodTitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProductDetailsResponseData) GetPrimaryGoodTitle() interface{} {
	if o == nil  {
		var ret interface{}
		return ret
	}
	return o.PrimaryGoodTitle
}

// GetPrimaryGoodTitleOk returns a tuple with the PrimaryGoodTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProductDetailsResponseData) GetPrimaryGoodTitleOk() (*interface{}, bool) {
	if o == nil || o.PrimaryGoodTitle == nil {
		return nil, false
	}
	return &o.PrimaryGoodTitle, true
}

// HasPrimaryGoodTitle returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasPrimaryGoodTitle() bool {
	if o != nil && o.PrimaryGoodTitle != nil {
		return true
	}

	return false
}

// SetPrimaryGoodTitle gets a reference to the given interface{} and assigns it to the PrimaryGoodTitle field.
func (o *GetProductDetailsResponseData) SetPrimaryGoodTitle(v interface{}) {
	o.PrimaryGoodTitle = v
}

// GetSellStatus returns the SellStatus field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetSellStatus() string {
	if o == nil || o.SellStatus == nil {
		var ret string
		return ret
	}
	return *o.SellStatus
}

// GetSellStatusOk returns a tuple with the SellStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetSellStatusOk() (*string, bool) {
	if o == nil || o.SellStatus == nil {
		return nil, false
	}
	return o.SellStatus, true
}

// HasSellStatus returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasSellStatus() bool {
	if o != nil && o.SellStatus != nil {
		return true
	}

	return false
}

// SetSellStatus gets a reference to the given string and assigns it to the SellStatus field.
func (o *GetProductDetailsResponseData) SetSellStatus(v string) {
	o.SellStatus = &v
}

// GetSellerId returns the SellerId field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetSellerId() float64 {
	if o == nil || o.SellerId == nil {
		var ret float64
		return ret
	}
	return *o.SellerId
}

// GetSellerIdOk returns a tuple with the SellerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetSellerIdOk() (*float64, bool) {
	if o == nil || o.SellerId == nil {
		return nil, false
	}
	return o.SellerId, true
}

// HasSellerId returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasSellerId() bool {
	if o != nil && o.SellerId != nil {
		return true
	}

	return false
}

// SetSellerId gets a reference to the given float64 and assigns it to the SellerId field.
func (o *GetProductDetailsResponseData) SetSellerId(v float64) {
	o.SellerId = &v
}

// GetStars returns the Stars field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetStars() string {
	if o == nil || o.Stars == nil {
		var ret string
		return ret
	}
	return *o.Stars
}

// GetStarsOk returns a tuple with the Stars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetStarsOk() (*string, bool) {
	if o == nil || o.Stars == nil {
		return nil, false
	}
	return o.Stars, true
}

// HasStars returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasStars() bool {
	if o != nil && o.Stars != nil {
		return true
	}

	return false
}

// SetStars gets a reference to the given string and assigns it to the Stars field.
func (o *GetProductDetailsResponseData) SetStars(v string) {
	o.Stars = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetState() string {
	if o == nil || o.State == nil {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetStateOk() (*string, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *GetProductDetailsResponseData) SetState(v string) {
	o.State = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetProductDetailsResponseData) SetStatus(v string) {
	o.Status = &v
}

// GetStatusInherited returns the StatusInherited field value if set, zero value otherwise.
func (o *GetProductDetailsResponseData) GetStatusInherited() string {
	if o == nil || o.StatusInherited == nil {
		var ret string
		return ret
	}
	return *o.StatusInherited
}

// GetStatusInheritedOk returns a tuple with the StatusInherited field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetStatusInheritedOk() (*string, bool) {
	if o == nil || o.StatusInherited == nil {
		return nil, false
	}
	return o.StatusInherited, true
}

// HasStatusInherited returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasStatusInherited() bool {
	if o != nil && o.StatusInherited != nil {
		return true
	}

	return false
}

// SetStatusInherited gets a reference to the given string and assigns it to the StatusInherited field.
func (o *GetProductDetailsResponseData) SetStatusInherited(v string) {
	o.StatusInherited = &v
}

// GetTag returns the Tag field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProductDetailsResponseData) GetTag() interface{} {
	if o == nil  {
		var ret interface{}
		return ret
	}
	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProductDetailsResponseData) GetTagOk() (*interface{}, bool) {
	if o == nil || o.Tag == nil {
		return nil, false
	}
	return &o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasTag() bool {
	if o != nil && o.Tag != nil {
		return true
	}

	return false
}

// SetTag gets a reference to the given interface{} and assigns it to the Tag field.
func (o *GetProductDetailsResponseData) SetTag(v interface{}) {
	o.Tag = v
}

// GetTitle returns the Title field value
func (o *GetProductDetailsResponseData) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *GetProductDetailsResponseData) GetTitleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *GetProductDetailsResponseData) SetTitle(v string) {
	o.Title = v
}

// GetTitleMode returns the TitleMode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProductDetailsResponseData) GetTitleMode() interface{} {
	if o == nil  {
		var ret interface{}
		return ret
	}
	return o.TitleMode
}

// GetTitleModeOk returns a tuple with the TitleMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProductDetailsResponseData) GetTitleModeOk() (*interface{}, bool) {
	if o == nil || o.TitleMode == nil {
		return nil, false
	}
	return &o.TitleMode, true
}

// HasTitleMode returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasTitleMode() bool {
	if o != nil && o.TitleMode != nil {
		return true
	}

	return false
}

// SetTitleMode gets a reference to the given interface{} and assigns it to the TitleMode field.
func (o *GetProductDetailsResponseData) SetTitleMode(v interface{}) {
	o.TitleMode = v
}

// GetTitleSuffix returns the TitleSuffix field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProductDetailsResponseData) GetTitleSuffix() string {
	if o == nil || o.TitleSuffix.Get() == nil {
		var ret string
		return ret
	}
	return *o.TitleSuffix.Get()
}

// GetTitleSuffixOk returns a tuple with the TitleSuffix field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProductDetailsResponseData) GetTitleSuffixOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.TitleSuffix.Get(), o.TitleSuffix.IsSet()
}

// HasTitleSuffix returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasTitleSuffix() bool {
	if o != nil && o.TitleSuffix.IsSet() {
		return true
	}

	return false
}

// SetTitleSuffix gets a reference to the given NullableString and assigns it to the TitleSuffix field.
func (o *GetProductDetailsResponseData) SetTitleSuffix(v string) {
	o.TitleSuffix.Set(&v)
}
// SetTitleSuffixNil sets the value for TitleSuffix to be an explicit nil
func (o *GetProductDetailsResponseData) SetTitleSuffixNil() {
	o.TitleSuffix.Set(nil)
}

// UnsetTitleSuffix ensures that no value is present for TitleSuffix, not even an explicit nil
func (o *GetProductDetailsResponseData) UnsetTitleSuffix() {
	o.TitleSuffix.Unset()
}

// GetUseGroupLinks returns the UseGroupLinks field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProductDetailsResponseData) GetUseGroupLinks() interface{} {
	if o == nil  {
		var ret interface{}
		return ret
	}
	return o.UseGroupLinks
}

// GetUseGroupLinksOk returns a tuple with the UseGroupLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProductDetailsResponseData) GetUseGroupLinksOk() (*interface{}, bool) {
	if o == nil || o.UseGroupLinks == nil {
		return nil, false
	}
	return &o.UseGroupLinks, true
}

// HasUseGroupLinks returns a boolean if a field has been set.
func (o *GetProductDetailsResponseData) HasUseGroupLinks() bool {
	if o != nil && o.UseGroupLinks != nil {
		return true
	}

	return false
}

// SetUseGroupLinks gets a reference to the given interface{} and assigns it to the UseGroupLinks field.
func (o *GetProductDetailsResponseData) SetUseGroupLinks(v interface{}) {
	o.UseGroupLinks = v
}

func (o GetProductDetailsResponseData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Brand != nil {
		toSerialize["brand"] = o.Brand
	}
	if o.BrandId != nil {
		toSerialize["brand_id"] = o.BrandId
	}
	if o.CategoryId != nil {
		toSerialize["category_id"] = o.CategoryId
	}
	if o.CommentsAmount != nil {
		toSerialize["comments_amount"] = o.CommentsAmount
	}
	if o.CommentsMark != nil {
		toSerialize["comments_mark"] = o.CommentsMark
	}
	if o.Config != nil {
		toSerialize["config"] = o.Config
	}
	if o.Discount != nil {
		toSerialize["discount"] = o.Discount
	}
	if o.Dispatch != nil {
		toSerialize["dispatch"] = o.Dispatch
	}
	if o.Docket != nil {
		toSerialize["docket"] = o.Docket
	}
	if o.Gift != nil {
		toSerialize["gift"] = o.Gift
	}
	if o.GroupId != nil {
		toSerialize["group_id"] = o.GroupId
	}
	if o.GroupName != nil {
		toSerialize["group_name"] = o.GroupName
	}
	if o.GroupTitle != nil {
		toSerialize["group_title"] = o.GroupTitle
	}
	if o.Groups != nil {
		toSerialize["groups"] = o.Groups
	}
	if o.Href != nil {
		toSerialize["href"] = o.Href
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.ImageMain != nil {
		toSerialize["image_main"] = o.ImageMain
	}
	if o.Images != nil {
		toSerialize["images"] = o.Images
	}
	if o.IsGroupPrimary != nil {
		toSerialize["is_group_primary"] = o.IsGroupPrimary
	}
	if o.IsNeedStreetId != nil {
		toSerialize["is_need_street_id"] = o.IsNeedStreetId
	}
	if o.MerchantId != nil {
		toSerialize["merchant_id"] = o.MerchantId
	}
	if o.Mpath != nil {
		toSerialize["mpath"] = o.Mpath
	}
	if o.OldPrice != nil {
		toSerialize["old_price"] = o.OldPrice
	}
	if o.ParentCategoryId != nil {
		toSerialize["parent_category_id"] = o.ParentCategoryId
	}
	if o.PlBonusChargePcs != nil {
		toSerialize["pl_bonus_charge_pcs"] = o.PlBonusChargePcs
	}
	if o.PlUseInstantBonus != nil {
		toSerialize["pl_use_instant_bonus"] = o.PlUseInstantBonus
	}
	if o.Premium != nil {
		toSerialize["premium"] = o.Premium
	}
	if o.Preorder != nil {
		toSerialize["preorder"] = o.Preorder
	}
	if o.Price != nil {
		toSerialize["price"] = o.Price
	}
	if o.PricePcs != nil {
		toSerialize["price_pcs"] = o.PricePcs
	}
	if o.PrimaryGoodTitle != nil {
		toSerialize["primary_good_title"] = o.PrimaryGoodTitle
	}
	if o.SellStatus != nil {
		toSerialize["sell_status"] = o.SellStatus
	}
	if o.SellerId != nil {
		toSerialize["seller_id"] = o.SellerId
	}
	if o.Stars != nil {
		toSerialize["stars"] = o.Stars
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.StatusInherited != nil {
		toSerialize["status_inherited"] = o.StatusInherited
	}
	if o.Tag != nil {
		toSerialize["tag"] = o.Tag
	}
	if true {
		toSerialize["title"] = o.Title
	}
	if o.TitleMode != nil {
		toSerialize["title_mode"] = o.TitleMode
	}
	if o.TitleSuffix.IsSet() {
		toSerialize["title_suffix"] = o.TitleSuffix.Get()
	}
	if o.UseGroupLinks != nil {
		toSerialize["use_group_links"] = o.UseGroupLinks
	}
	return json.Marshal(toSerialize)
}

type NullableGetProductDetailsResponseData struct {
	value *GetProductDetailsResponseData
	isSet bool
}

func (v NullableGetProductDetailsResponseData) Get() *GetProductDetailsResponseData {
	return v.value
}

func (v *NullableGetProductDetailsResponseData) Set(val *GetProductDetailsResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProductDetailsResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProductDetailsResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProductDetailsResponseData(val *GetProductDetailsResponseData) *NullableGetProductDetailsResponseData {
	return &NullableGetProductDetailsResponseData{value: val, isSet: true}
}

func (v NullableGetProductDetailsResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProductDetailsResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


